---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    sysctl_settings:
      fs.file-max: 1000000
      fs.inotify.max_user_watches: 16777216
      kernel.core_uses_pid: 1
      kernel.msgmax: 8192
      kernel.msgmnb: 16384
      net.core.somaxconn: 65535
      net.core.netdev_max_backlog: 16384
      net.ipv4.ip_forward: 0
      net.ipv4.conf.all.accept_redirects: 1
      net.ipv4.conf.default.accept_redirects: 0

  tasks:
    - name: set sysctl settings
      sysctl: sysctl_set=yes reload=yes state=present
        name="{{ item.key }}"
        value="{{ item.value }}"
      with_dict: "{{ sysctl_settings }}"
